# i want to export this list

subjects_array = [
'Aerospace Studies', 'Afro-American Studies', 'Animal Science', 
'Anthropology', 'Anthropology - @Amherst', 'Arabic', 'Architecture', 'Art', 
'Art History', 'Arts Extension', 'Asian - @Amherst', 'Asian Studies', 'Astronomy', 
'Astronomy - @Amherst', 'Astronomy - @Mt Holyoke', 'Astronomy - @Smith', 
"Bachelor's Deg. W/Indiv Conc.", 'Biochemistry & Molecular Bio.', 'Biology', 
'Biology - @Amherst', 'Biomedical Engineering', 'Biostatistics', 
'Black Studies - @Amherst', 'Building & Construction Tech', 'Catalan', 
'Chemical Engineering', 'Chemistry', 'Chinese', 'Civil & Environmental Engrg', 
'Classics', 'College of Inform & Comp Sci', 'Communication', 
'Communication Disorders', 'Comparative Literature', 'Computer Science', 
'Critical Social Inq - @Hamp', 'Dance', 'Dance - @Mt Holyoke', 'Dance - @Smith', 
'Data Analytics and Computation', 'East Asian Literature - @Smith', 'Economics', 
'Economics - @Smith', 'Education', 'Electrical & Computer Engin', 'Engineering', 
'English', 'English - @Amherst', 'English Lang.& Lit. - @Smith', 
'English Writing Program', 'English as a Second Language', 
'Environmental Conservation', 'Environmental Health Sciences', 
'Environmental Science', 'Environmental Science - @Smith', 'Epidemiology', 
'Faculty First Year Seminars', 'Film & Media Studies -@Amherst', 'Film Studies', 
'Finance', 'First Year Seminar', 'Five Coll Ctr: World Languages', 'Food Science', 
'French Studies', 'Geography', 'Geology', 'Geology - @Amherst', 'Geosciences', 
'German', 'Government - @Smith', 'Graduate School', 'Greek', 
'Health Promotion & Policy', 'Hebrew', 'Hispanic Lit. & Linguistics', 'History', 
'History - @Mt Holyoke', 'History - @Smith', 'Honors College', 
'Hospitality & Tourism Managmnt', 'Human Development', 
'Human.,Arts,&Cult.- @Hampshire', 'Humanities and Fine Arts', 'ICons', 
'Informatics', 'Isenberg School of Management', 'Italian Studies', 'Japanese', 
'Journalism', 'Judaic Studies', 'Kinesiology', 'Korean', 'Korean - @Smith', 
'LL: Art & Photography', 'LL: Arts Management', 'LL: Career & Personal Develpmt', 
'LL: Languages', 'LL: Music', 'LL: Study Skills & Test Taking', 
'LL: Summer College', 'LL: Yestermorrow Program', 'Labor Studies', 
'Landscape Architecture', 'Landscape Contracting', 
'Languages, Literature&Culture', 'Latin', 'Latin-Student Teaching', 
'Law,Jur&SocThought - @Amherst', 'Legal Studies', 'Linguistics', 'Management', 
'Marketing', 'Materials Science and Engineer', 'Mathematics', 
'Mathematics - @Amherst', 'Mechanical & Industrial Engrg', 'Microbiology', 
'Middle Eastern Studies', 'Military Leadership', 'Music', 'Music - @Amherst', 
'Music - @Mt Holyoke', 'Music - @Smith', 'Music & Dance - @Hamp', 'Nanotechnology', 
'Natural Sciences - @Smith', 'Near Eastern Studies - @Amherst', 
'Near Eastern Studies - @Smith', 'Nursing', 'Nutrition', 'Operations & Info Mgmt', 
'Organismic & Evolutionary Biol', 'Philosophy', 'Philosophy - @Amherst', 
'Philosophy - @Hamp', 'Physics', 'Physics - @Amherst', 
'Physics - @Mt Holyoke', 'Physics - @Smith', 'Plant & Soil Sciences', 
'Plant Biology', 'Political Science', 'Political Science - @Smith', 
'Portuguese', 'Pre-Med/Pre-Health Advising', 'Psychology', 
'Psychology - @Amherst', 'Psychology - @Smith', 'Public Health', 
'Public Policy & Admin', 'Resource Economics', 'Russian, E Euro & Eurasian St', 
'School of Public Policy', 'School of Public Health & Hlth', 'Social Thought - @Smith', 
'Sociology', 'Sociology - @Amherst', 'Sociology - @Smith', 'Spanish', 
'Sport Management', 'Stockbridge School', 'Studio Art - @Hamp', 
'Studio Art - @Mt Holyoke', 'Sustainable Community Dev', 
'Theater', 'Theater - @Amherst', 'Theater - @Hamp', 'Theater - @Smith', 
'UWW-Interdisciplinary Studies', 'UWW-Prior Learning', 'UWW-Urban Studies', 
'University Without Walls', 'University Writing Program', 
'Veterans and Active Military', 'Veterinary and Animal Science', 
'WGSS - @Amherst', 'WGSS - @Hamp', 'WGSS - @Mt Holyoke', 
'Women, Gender, Sexuality Std', 'World Languages Institute', 'Writing', 
'Zoology'
]

